#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

start_service() {
    echo "starting netaidkit."
    procd_open_instance
    procd_set_param command /usr/bin/nakd
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-999}
    procd_close_instance
}

boot() {
    # Clear LEDS
    echo "0" > /sys/class/leds/gl-inet\:green\:lan/brightness
    echo "0" > /sys/class/leds/gl-inet\:red\:wlan/brightness

    # Set domain socket permissions
    chgrp www-data /run/nakd
    chmod g+w /run/nakd

    start
}
